# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4e42970b4bb1464c8f5d52dc7ee733035142c6e196a4612bdc3309ef695b2ea4da0293aa8bb676933accf28a2f619f6a3a7f1daf8e16f6faddc07caf44245ed

test:
  secret_key_base: 1b076be3156205c97db3cbfa729288773c34aba1154c9a604879be6f6f3b1dd0806cb6c296090b7dd6aa9630130db650afe7a7cc5bb2a76e471cb31ba2180154

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
